module.exports = {
  error: "ERROR",
  success: "SUCCESS",
  setuser: "SET-USER",
  signuserupforgame: "SIGN-UP-FOR-GAME",
  getgameobject: "GET-GAME",
  setgameobject: "SET-GAME",
  blockout: "BLOCK-OUT",
  newuserjoined: "NEW-USER",
  youwin: "WIN",
  totalwinnersreached: "TOTAL-WINNERS-REACHED",
  wronganswer: "WRONG-ANSWER",
  submitanswer: "SUBMIT-ANSWER",
  updateuserprofile: "UPDATE-PROFILE",
  turngameonoroff: "TURN-ON-OFF",
  updategameobject: "UPDATE-GAME-OBJECT",
  verifyaccount: "VERIFY",
  passwordreset: "PASSWORDRESET",
  verifyreset: "VERIFYRESET",
  resetuser: "RESETUSER",
  withdrawcash: "WITHDRAW-CASH"
};
